[project]
name = "pyvision"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Selim Youssry", email = "selimyoussry@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.4.6",
    "opencv-python-headless>=5.0.0.93",
    "pillow>=12.3.0",
]

[project.scripts]
pyvision = "pyvision:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
